
PROJECTION_MAP_1 = "map_1"
PROJECTION_MAP_2 = "map_2"
PROJECTION_CURVE_1 = "curve_1"
PROJECTION_CURVE_2 = "curve_2"

PROJECTION_SPLIT_LIMIT = 50  # 50th department

CHART_DATE_TIME_FORMAT_STRING = '%Y%m%d%H%M'