# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 14:33
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSMArrondissements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insee_ar', models.CharField(max_length=80)),
                ('nom', models.CharField(max_length=80)),
                ('wikipedia', models.CharField(max_length=80)),
                ('nb_comm', models.BigIntegerField()),
                ('surf_km2', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='OSMCommunes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insee', models.CharField(max_length=80)),
                ('nom', models.CharField(max_length=80)),
                ('wikipedia', models.CharField(max_length=80)),
                ('surf_m2', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='OSMDepartements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_insee', models.CharField(max_length=80)),
                ('nom', models.CharField(max_length=80)),
                ('nuts3', models.CharField(max_length=80)),
                ('wikipedia', models.CharField(max_length=80)),
                ('wikidata', models.CharField(max_length=80)),
                ('surf_ha', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='OSMRegions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insee', models.CharField(max_length=80)),
                ('nom', models.CharField(max_length=80)),
                ('wikipedia', models.CharField(max_length=80)),
                ('wikidata', models.CharField(max_length=80)),
                ('surf_ha', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
