# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_osmarrondissements_osmcommunes_osmdepartements_osmregions'),
    ]

    operations = [
        migrations.AddField(
            model_name='osmcommunes',
            name='geocode',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='osmdepartements',
            name='geocode',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
