# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-06 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortid', models.CharField(db_index=True, max_length=6, verbose_name='Identifiant alphanumérique court')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('framing_parameters', jsonfield.fields.JSONField(blank=True, default=[])),
                ('territory_groups', jsonfield.fields.JSONField(blank=True, default=[])),
                ('simu_type', models.CharField(blank=True, default='scan', max_length=4)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='accounts.Account')),
            ],
            options={
                'ordering': ('-date', '-pk'),
            },
        ),
    ]
